### ISSUE TITLE
Organização do RoadMap

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2023-1-MeasureSoftGram-Doc#83]
## Descrição da Issue
Criação e Organização do Roadmap do Produto

## Tarefas:

- [x] Criação das Milestones
- [x] Criação dos Épicos.
- [x] Organização da Estrutura.
- [x] Designar issues aos epicos

## Critérios de Aceitação:

- [x] RoadMap está de acordo com a EAP
- [x] Epicos estarem organizados
